### ISSUE TITLE
Where are the barrels and another attachmens?

### ISSUE THREAD

**Issue by blastdarkness** [CurlySparkle/ARC9-COD2019#26]
In this latest update, the barrels and magazines of several weapons are missing, in addition, several special attachmens are now missing. Is it a mistake or part of the developmen?

**Comment by CurlySparkle** [comment]
Part of the development since most of these attachs are weapon specific so best to put them on the shared pack (less file space/usage) as for the attachments that are missing, they are being merged into one file depending of the weapon type for the same reason to avoid too many file usage and less chance of breaking if other mods are used with too many files.
