### ISSUE TITLE
big issue with animations

### ISSUE THREAD

**Issue by JessuG1** [CurlySparkle/ARC9-COD2019#55]
The weapon swings even when I'm standing still, how can I fix it?
video - https://youtu.be/x6mSGAwAeSs
my addons - https://steamcommunity.com/sharedfiles/filedetails/?id=3260597674

**Comment by CurlySparkle** [comment]
The issue happens if you speed is below 100 it ends up conflicting with how the movement setup is done on the pack, sadly there isn't much that i can do to fix this, the only workaround for now is people not to go below 100 on the move speed, there's one that i use tho which is called Better Movement, recommend it, this is my speed settings of it either way.
![stuff](https://github.com/CurlySparkle/ARC9-COD2019/assets/5094277/ef7b2e7c-3b7f-4c58-a208-2e01d585b30b)
